### ISSUE TITLE
SpotzSDK duplicates AFNetworking Classes

### ISSUE THREAD

**Issue by JCurativo** [localz/Spotz-iOS-SDK#1]
I have an issue in setting up Spotz.

We're using cocoapods, so I only added this line,
pod 'SpotzSDK', :git => 'https://github.com/localz/Spotz-iOS-SDK.git'
then 'pod install'

Our project also uses AFNetworking, so we also have AFNetworking installed via cocoapods. The problem is that SpotzSDK seems to be also using AFNetworking and is duplicating the classes. If I also remove AFNetworking, I'll get errors in my class that uses AFNetworking. And I also can't (of course) delete it from SpotzSDK.framework.

Any work around on this issue? 

![spotzsdk duplicates afnetworking classes](https://cloud.githubusercontent.com/assets/1849082/6591453/185ff93a-c7fb-11e4-8a0d-437bf9f36349.png)

Many Thanks!!
Jennifer

**Comment by dsykesturner** [comment]
Hi Jennifer,

We are aware of this issue and it is currently being fixed. If you need an instant work around, you can use an older commit of version 1 SpotzSDK. 

Daniel

**Comment by dsykesturner** [comment]
Hi Jennifer,

Check out our latest push. To avoid the clash, AFNetworking is now a public dependency of SpotzSDK so will use the version you are using (and latest if none).
If you have any more troubles, open up an issue again.

Daniel

**Comment by JCurativo** [comment]
Thanks Daniel, will check it out.


Jennifer
