### ISSUE TITLE
Error installing SpotzSDK (Cocoapods)

### ISSUE THREAD

**Issue by JCurativo** [localz/Spotz-iOS-SDK#2]
In relation to fix to this issue: https://github.com/localz/Spotz-iOS-SDK/issues/1#event-250060320

Daniel mentioned to checkout the latest push. And I just wondered how, since I actually installed Spotz into our project using Cocoapods. 
So I thought calling "pod install" might re-install and check new updates for SpotzSDK.
But I got this error, instead:

![error installing spotzsdk](https://cloud.githubusercontent.com/assets/1849082/6601429/9c6b2f56-c850-11e4-8106-ec5c1bda6a25.png)

**Comment by dsykesturner** [comment]
Hi Jennifer,

pod install is used to install your pods and a podfile.lock the first time only. It hasn't downloaded the latest version (2.0.0.1) here. To update pods use pod update. If you are still getting the issue, delete podfile.lock and the pods folder then run pod install again.

Daniel

**Comment by JCurativo** [comment]
Hi Daniel, I honestly didn't know that (pod update), Thank you very much! It's fixed now.
