### ISSUE TITLE
Constraint 'I' expects an integer constant expression in Xcode 7.0

### ISSUE THREAD

**Issue by johnvega** [localz/Spotz-iOS-SDK#3]
Hi Author,

I have an issue in running the SpotzSDK in xcode 7 (Xcode 7.0 version) simulator but not in xcode6.4 simulator.

The error is : /Pods/Headers/Private/Realm/tightdb/tightdb_nmmintrin.h:38:79: Constraint 'I' expects an integer constant expression

Thanks, John

**Comment by dsykesturner** [comment]
Hi John,

Please use Spotz v3 instead (found here: https://github.com/localz/Spotz3-iOS-SDK ) as it is still supported. It has a very similar initialisation method and works just about the same (and better!). 

Also please use the newer corresponding console to manage the beacons (found here: https://console.localz.io )

Thanks,
Daniel

**Comment by johnvega** [comment]
Hi Daniel,

Thank you for your fast reply. it's fix now, thanks.. 

also i notice in the link :  https://github.com/localz/Spotz3-iOS-SDK that your readme installation has the pod old link i.e "pod 'SpotzSDK', :git => 'https://github.com/localz/Spotz-iOS-SDK.git'" so i made an adjustment for the new pod link to "https://github.com/localz/Spotz3-iOS-SDK.git"


Thank, John

**Comment by dsykesturner** [comment]
Yes you're right there, the read me is still being updated so step 4 may not currently be correct either.

Thanks,
Daniel
